// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Vservesafe_gateway_screen

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TagsHolderPanel = lv_obj_create(ui_HomeScreen);
lv_obj_set_width( ui_TagsHolderPanel, 450);
lv_obj_set_height( ui_TagsHolderPanel, 195);
lv_obj_set_x( ui_TagsHolderPanel, 0 );
lv_obj_set_y( ui_TagsHolderPanel, -10 );
lv_obj_set_align( ui_TagsHolderPanel, LV_ALIGN_CENTER );
lv_obj_set_scroll_dir(ui_TagsHolderPanel, LV_DIR_HOR);
lv_obj_set_style_pad_left(ui_TagsHolderPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TagsHolderPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TagsHolderPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TagsHolderPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TagPanelT = lv_obj_create(ui_TagsHolderPanel);
lv_obj_set_width( ui_TagPanelT, 80);
lv_obj_set_height( ui_TagPanelT, 80);
lv_obj_clear_flag( ui_TagPanelT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TagPanelT, lv_color_hex(0xFEFFF3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TagPanelT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TagPanelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TagPanelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TagPanelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TagPanelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_TagPanelT, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TagPanelT, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TagPanelT, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TagPanelT, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_TagInnerPanelT = lv_obj_create(ui_TagPanelT);
lv_obj_set_width( ui_TagInnerPanelT, 60);
lv_obj_set_height( ui_TagInnerPanelT, 55);
lv_obj_set_align( ui_TagInnerPanelT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TagInnerPanelT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TagInnerPanelT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TagInnerPanelT, lv_color_hex(0xFFFFD0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TagInnerPanelT, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TagInnerPanelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TagInnerPanelT, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TagInnerPanelT, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TagInnerPanelT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TagInnerPanelT, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TagCRHLabelT = lv_label_create(ui_TagInnerPanelT);
lv_obj_set_width( ui_TagCRHLabelT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TagCRHLabelT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TagCRHLabelT, 0 );
lv_obj_set_y( ui_TagCRHLabelT, 4 );
lv_obj_set_align( ui_TagCRHLabelT, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TagCRHLabelT,"C\n%R");
lv_obj_set_style_text_letter_space(ui_TagCRHLabelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TagCRHLabelT, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TagCRHLabelT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TagCRHLabelT, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TagTempLabelT = lv_label_create(ui_TagInnerPanelT);
lv_obj_set_width( ui_TagTempLabelT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TagTempLabelT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TagTempLabelT, -10 );
lv_obj_set_y( ui_TagTempLabelT, -9 );
lv_obj_set_align( ui_TagTempLabelT, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TagTempLabelT,"00.0");
lv_obj_set_style_text_letter_space(ui_TagTempLabelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TagTempLabelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TagTempLabelT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TagTempLabelT, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TagHumidLabelT = lv_label_create(ui_TagInnerPanelT);
lv_obj_set_width( ui_TagHumidLabelT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TagHumidLabelT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TagHumidLabelT, -18 );
lv_obj_set_y( ui_TagHumidLabelT, 12 );
lv_obj_set_align( ui_TagHumidLabelT, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TagHumidLabelT,"100");
lv_obj_set_style_text_letter_space(ui_TagHumidLabelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TagHumidLabelT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TagHumidLabelT, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TagHumidLabelT, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TagNameLabelT = lv_label_create(ui_TagPanelT);
lv_obj_set_width( ui_TagNameLabelT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TagNameLabelT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TagNameLabelT, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_TagNameLabelT,"Name");
lv_obj_set_style_text_font(ui_TagNameLabelT, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TagMacLabelT = lv_label_create(ui_TagPanelT);
lv_obj_set_width( ui_TagMacLabelT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TagMacLabelT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TagMacLabelT, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_TagMacLabelT,"MAC");
lv_obj_set_style_text_font(ui_TagMacLabelT, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusPanel = lv_obj_create(ui_HomeScreen);
lv_obj_set_width( ui_StatusPanel, 480);
lv_obj_set_height( ui_StatusPanel, 35);
lv_obj_set_x( ui_StatusPanel, 0 );
lv_obj_set_y( ui_StatusPanel, -140 );
lv_obj_set_align( ui_StatusPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_StatusPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_StatusPanel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_StatusPanel, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_StatusPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_StatusPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_StatusPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiStatusImage = lv_img_create(ui_StatusPanel);
lv_img_set_src(ui_WifiStatusImage, &ui_img_wifi_png);
lv_obj_set_width( ui_WifiStatusImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_WifiStatusImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_WifiStatusImage, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_WifiStatusImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WifiStatusImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WifiOffStatusImage = lv_img_create(ui_StatusPanel);
lv_img_set_src(ui_WifiOffStatusImage, &ui_img_wifi_off_png);
lv_obj_set_width( ui_WifiOffStatusImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_WifiOffStatusImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_WifiOffStatusImage, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_WifiOffStatusImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WifiOffStatusImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BLEStatusImage = lv_img_create(ui_StatusPanel);
lv_img_set_src(ui_BLEStatusImage, &ui_img_bluetooth_png);
lv_obj_set_width( ui_BLEStatusImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_BLEStatusImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_BLEStatusImage, -28 );
lv_obj_set_y( ui_BLEStatusImage, 0 );
lv_obj_set_align( ui_BLEStatusImage, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_BLEStatusImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BLEStatusImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ServerStatusImage = lv_img_create(ui_StatusPanel);
lv_img_set_src(ui_ServerStatusImage, &ui_img_clouds_png);
lv_obj_set_width( ui_ServerStatusImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_ServerStatusImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_ServerStatusImage, -56 );
lv_obj_set_y( ui_ServerStatusImage, 0 );
lv_obj_set_align( ui_ServerStatusImage, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ServerStatusImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ServerStatusImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ServerOffStatusImage = lv_img_create(ui_StatusPanel);
lv_img_set_src(ui_ServerOffStatusImage, &ui_img_cloud_slash_png);
lv_obj_set_width( ui_ServerOffStatusImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_ServerOffStatusImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_ServerOffStatusImage, -56 );
lv_obj_set_y( ui_ServerOffStatusImage, 0 );
lv_obj_set_align( ui_ServerOffStatusImage, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ServerOffStatusImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ServerOffStatusImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AlarmStatusImage = lv_img_create(ui_StatusPanel);
lv_img_set_src(ui_AlarmStatusImage, &ui_img_bell_png);
lv_obj_set_width( ui_AlarmStatusImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_AlarmStatusImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_AlarmStatusImage, -84 );
lv_obj_set_y( ui_AlarmStatusImage, 0 );
lv_obj_set_align( ui_AlarmStatusImage, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_AlarmStatusImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_AlarmStatusImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AlarmOffStatusImage = lv_img_create(ui_StatusPanel);
lv_img_set_src(ui_AlarmOffStatusImage, &ui_img_bell_slash_png);
lv_obj_set_width( ui_AlarmOffStatusImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_AlarmOffStatusImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_AlarmOffStatusImage, -84 );
lv_obj_set_y( ui_AlarmOffStatusImage, 0 );
lv_obj_set_align( ui_AlarmOffStatusImage, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_AlarmOffStatusImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_AlarmOffStatusImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TitleLabel = lv_label_create(ui_StatusPanel);
lv_obj_set_width( ui_TitleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TitleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TitleLabel, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_TitleLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_TitleLabel,"Home");

ui_ToOptionButton = lv_btn_create(ui_HomeScreen);
lv_obj_set_width( ui_ToOptionButton, 62);
lv_obj_set_height( ui_ToOptionButton, 60);
lv_obj_set_x( ui_ToOptionButton, 2 );
lv_obj_set_y( ui_ToOptionButton, 0 );
lv_obj_set_align( ui_ToOptionButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_ToOptionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ToOptionButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ToOptionButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ToOptionButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ToOptionButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ToOptionButton, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ToOptionButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ToOptionButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ToOptionImage = lv_img_create(ui_ToOptionButton);
lv_img_set_src(ui_ToOptionImage, &ui_img_gear_png);
lv_obj_set_width( ui_ToOptionImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_ToOptionImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_ToOptionImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ToOptionImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ToOptionImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ToOptionImage,384);

ui_HomeLogoImage = lv_img_create(ui_HomeScreen);
lv_img_set_src(ui_HomeLogoImage, &ui_img_142471982);
lv_obj_set_width( ui_HomeLogoImage, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_HomeLogoImage, LV_SIZE_CONTENT);   /// 98
lv_obj_set_x( ui_HomeLogoImage, -180 );
lv_obj_set_y( ui_HomeLogoImage, 130 );
lv_obj_set_align( ui_HomeLogoImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeLogoImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HomeLogoImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_HomeLogoImage,128);

ui_TagCountLabel = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_TagCountLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TagCountLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TagCountLabel, 0 );
lv_obj_set_y( ui_TagCountLabel, 130 );
lv_obj_set_align( ui_TagCountLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TagCountLabel,"8/8");
lv_obj_set_style_text_font(ui_TagCountLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TagSpinner = lv_spinner_create(ui_HomeScreen,1000,90);
lv_obj_set_width( ui_TagSpinner, 80);
lv_obj_set_height( ui_TagSpinner, 80);
lv_obj_set_align( ui_TagSpinner, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TagSpinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_add_event_cb(ui_TagsHolderPanel, ui_event_TagsHolderPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ToOptionButton, ui_event_ToOptionButton, LV_EVENT_ALL, NULL);

}
