// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Vservesafe_gateway_screen

#include "../ui.h"

void ui_InputScreen_screen_init(void)
{
ui_InputScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_InputScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InputSaveButton = lv_btn_create(ui_InputScreen);
lv_obj_set_width( ui_InputSaveButton, 62);
lv_obj_set_height( ui_InputSaveButton, 60);
lv_obj_set_x( ui_InputSaveButton, 2 );
lv_obj_set_y( ui_InputSaveButton, 0 );
lv_obj_set_align( ui_InputSaveButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_InputSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InputSaveButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_InputSaveButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_InputSaveButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InputSaveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InputSaveButton, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InputSaveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_InputSaveButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InputSaveImage = lv_img_create(ui_InputSaveButton);
lv_img_set_src(ui_InputSaveImage, &ui_img_check_png);
lv_obj_set_width( ui_InputSaveImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_InputSaveImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_InputSaveImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InputSaveImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_InputSaveImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_InputSaveImage,384);

ui_InputBackButton = lv_btn_create(ui_InputScreen);
lv_obj_set_width( ui_InputBackButton, 62);
lv_obj_set_height( ui_InputBackButton, 60);
lv_obj_set_x( ui_InputBackButton, -2 );
lv_obj_set_y( ui_InputBackButton, 0 );
lv_obj_set_align( ui_InputBackButton, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_InputBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InputBackButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_InputBackButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_InputBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InputBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InputBackButton, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InputBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_InputBackButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InputBackImage = lv_img_create(ui_InputBackButton);
lv_img_set_src(ui_InputBackImage, &ui_img_arrow_left_png);
lv_obj_set_width( ui_InputBackImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_InputBackImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_InputBackImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InputBackImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_InputBackImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_InputBackImage,384);

ui_InputTextArea = lv_textarea_create(ui_InputScreen);
lv_obj_set_width( ui_InputTextArea, 440);
lv_obj_set_height( ui_InputTextArea, LV_SIZE_CONTENT);   /// 41
lv_obj_set_x( ui_InputTextArea, 0 );
lv_obj_set_y( ui_InputTextArea, -90 );
lv_obj_set_align( ui_InputTextArea, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_InputTextArea,32);
lv_textarea_set_placeholder_text(ui_InputTextArea,"Placeholder...");
lv_textarea_set_one_line(ui_InputTextArea,true);
lv_obj_set_style_text_font(ui_InputTextArea, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_InputKeyboard = lv_keyboard_create(ui_InputScreen);
lv_obj_set_width( ui_InputKeyboard, 460);
lv_obj_set_height( ui_InputKeyboard, 165);
lv_obj_set_x( ui_InputKeyboard, 0 );
lv_obj_set_y( ui_InputKeyboard, 15 );
lv_obj_set_align( ui_InputKeyboard, LV_ALIGN_CENTER );

ui_InputResetButton = lv_btn_create(ui_InputScreen);
lv_obj_set_width( ui_InputResetButton, 62);
lv_obj_set_height( ui_InputResetButton, 60);
lv_obj_set_align( ui_InputResetButton, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_InputResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InputResetButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_InputResetButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_InputResetButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_InputResetButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_InputResetButton, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_InputResetButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_InputResetButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InputResetImage = lv_img_create(ui_InputResetButton);
lv_img_set_src(ui_InputResetImage, &ui_img_arrow_cc_png);
lv_obj_set_width( ui_InputResetImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_InputResetImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_InputResetImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InputResetImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_InputResetImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_InputResetImage,384);

lv_obj_add_event_cb(ui_InputSaveButton, ui_event_InputSaveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_InputBackButton, ui_event_InputBackButton, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_InputKeyboard,ui_InputTextArea);
lv_obj_add_event_cb(ui_InputResetButton, ui_event_InputResetButton, LV_EVENT_ALL, NULL);

}
