// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Vservesafe_gateway_screen

#include "../ui.h"

void ui_OptionScreen_screen_init(void)
{
ui_OptionScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_OptionScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OptionPanelHolder = lv_obj_create(ui_OptionScreen);
lv_obj_set_width( ui_OptionPanelHolder, 450);
lv_obj_set_height( ui_OptionPanelHolder, 195);
lv_obj_set_x( ui_OptionPanelHolder, 0 );
lv_obj_set_y( ui_OptionPanelHolder, -10 );
lv_obj_set_align( ui_OptionPanelHolder, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_OptionPanelHolder,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_OptionPanelHolder, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_scroll_dir(ui_OptionPanelHolder, LV_DIR_VER);
lv_obj_set_style_pad_left(ui_OptionPanelHolder, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_OptionPanelHolder, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_OptionPanelHolder, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_OptionPanelHolder, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OptionListPanelHolderT = lv_obj_create(ui_OptionPanelHolder);
lv_obj_set_width( ui_OptionListPanelHolderT, 430);
lv_obj_set_height( ui_OptionListPanelHolderT, 40);
lv_obj_set_align( ui_OptionListPanelHolderT, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_OptionListPanelHolderT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OptionListPanelHolderT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OptionListPanelHolderT, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_OptionListPanelHolderT, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_OptionListPanelHolderT, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_OptionListPanelHolderT, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_OptionListPanelHolderT, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OptionListLabelT = lv_label_create(ui_OptionListPanelHolderT);
lv_obj_set_width( ui_OptionListLabelT, 360);
lv_obj_set_height( ui_OptionListLabelT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OptionListLabelT, 18 );
lv_obj_set_y( ui_OptionListLabelT, 0 );
lv_obj_set_align( ui_OptionListLabelT, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_OptionListLabelT,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_OptionListLabelT,"[WiFi SSID]");
lv_obj_set_style_text_font(ui_OptionListLabelT, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OptionNextImageT = lv_img_create(ui_OptionListPanelHolderT);
lv_img_set_src(ui_OptionNextImageT, &ui_img_chevron_right_png);
lv_obj_set_width( ui_OptionNextImageT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OptionNextImageT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_OptionNextImageT, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_OptionNextImageT, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OptionNextImageT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OptionEditMarkImageT = lv_img_create(ui_OptionListPanelHolderT);
lv_img_set_src(ui_OptionEditMarkImageT, &ui_img_asterisk_png);
lv_obj_set_width( ui_OptionEditMarkImageT, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OptionEditMarkImageT, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_OptionEditMarkImageT, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_OptionEditMarkImageT, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OptionEditMarkImageT, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OptionSaveButton = lv_btn_create(ui_OptionScreen);
lv_obj_set_width( ui_OptionSaveButton, 62);
lv_obj_set_height( ui_OptionSaveButton, 60);
lv_obj_set_x( ui_OptionSaveButton, 2 );
lv_obj_set_y( ui_OptionSaveButton, 0 );
lv_obj_set_align( ui_OptionSaveButton, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_OptionSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_OptionSaveButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_OptionSaveButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OptionSaveButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OptionSaveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OptionSaveButton, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OptionSaveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OptionSaveButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OptionSaveImage = lv_img_create(ui_OptionSaveButton);
lv_img_set_src(ui_OptionSaveImage, &ui_img_check_png);
lv_obj_set_width( ui_OptionSaveImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_OptionSaveImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_OptionSaveImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OptionSaveImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OptionSaveImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OptionSaveImage,384);

ui_OptionBackButton = lv_btn_create(ui_OptionScreen);
lv_obj_set_width( ui_OptionBackButton, 62);
lv_obj_set_height( ui_OptionBackButton, 60);
lv_obj_set_x( ui_OptionBackButton, -2 );
lv_obj_set_y( ui_OptionBackButton, 0 );
lv_obj_set_align( ui_OptionBackButton, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_OptionBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_OptionBackButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_OptionBackButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OptionBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OptionBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OptionBackButton, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OptionBackButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OptionBackButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OptionBackImage = lv_img_create(ui_OptionBackButton);
lv_img_set_src(ui_OptionBackImage, &ui_img_arrow_left_png);
lv_obj_set_width( ui_OptionBackImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_OptionBackImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_OptionBackImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OptionBackImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OptionBackImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OptionBackImage,384);

ui_OptionResetButton = lv_btn_create(ui_OptionScreen);
lv_obj_set_width( ui_OptionResetButton, 62);
lv_obj_set_height( ui_OptionResetButton, 60);
lv_obj_set_align( ui_OptionResetButton, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_OptionResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_OptionResetButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_OptionResetButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OptionResetButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OptionResetButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OptionResetButton, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OptionResetButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OptionResetButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OptionResetImage = lv_img_create(ui_OptionResetButton);
lv_img_set_src(ui_OptionResetImage, &ui_img_arrow_cc_png);
lv_obj_set_width( ui_OptionResetImage, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_OptionResetImage, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_OptionResetImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OptionResetImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_OptionResetImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_OptionResetImage,384);

lv_obj_add_event_cb(ui_OptionSaveButton, ui_event_OptionSaveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_OptionBackButton, ui_event_OptionBackButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_OptionResetButton, ui_event_OptionResetButton, LV_EVENT_ALL, NULL);

}
