// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Vservesafe_gateway_screen

#include "../ui.h"

void ui_SplashScreen_screen_init(void)
{
ui_SplashScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ColdsensesLogo = lv_img_create(ui_SplashScreen);
lv_img_set_src(ui_ColdsensesLogo, &ui_img_142471982);
lv_obj_set_width( ui_ColdsensesLogo, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_ColdsensesLogo, LV_SIZE_CONTENT);   /// 98
lv_obj_set_x( ui_ColdsensesLogo, 0 );
lv_obj_set_y( ui_ColdsensesLogo, -35 );
lv_obj_set_align( ui_ColdsensesLogo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ColdsensesLogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ColdsensesLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ColdsensesLogo,400);

ui_LoadingLabel = lv_label_create(ui_SplashScreen);
lv_obj_set_width( ui_LoadingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoadingLabel, 0 );
lv_obj_set_y( ui_LoadingLabel, -30 );
lv_obj_set_align( ui_LoadingLabel, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LoadingLabel,"LOADING...");
lv_obj_set_style_text_font(ui_LoadingLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
