// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Vservesafe_gateway_screen

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SpinnerSpin_Animation( lv_obj_t *TargetObject, int delay);
void TagBlur_Animation( lv_obj_t *TargetObject, int delay);
void TagUnblur_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t *ui_SplashScreen;
lv_obj_t *ui_ColdsensesLogo;
lv_obj_t *ui_LoadingLabel;


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t *ui_HomeScreen;
void ui_event_TagsHolderPanel( lv_event_t * e);
lv_obj_t *ui_TagsHolderPanel;
lv_obj_t *ui_TagPanelT;
lv_obj_t *ui_TagInnerPanelT;
lv_obj_t *ui_TagCRHLabelT;
lv_obj_t *ui_TagTempLabelT;
lv_obj_t *ui_TagHumidLabelT;
lv_obj_t *ui_TagNameLabelT;
lv_obj_t *ui_TagMacLabelT;
lv_obj_t *ui_StatusPanel;
lv_obj_t *ui_WifiStatusImage;
lv_obj_t *ui_WifiOffStatusImage;
lv_obj_t *ui_BLEStatusImage;
lv_obj_t *ui_ServerStatusImage;
lv_obj_t *ui_ServerOffStatusImage;
lv_obj_t *ui_AlarmStatusImage;
lv_obj_t *ui_AlarmOffStatusImage;
lv_obj_t *ui_TitleLabel;
void ui_event_ToOptionButton( lv_event_t * e);
lv_obj_t *ui_ToOptionButton;
lv_obj_t *ui_ToOptionImage;
lv_obj_t *ui_HomeLogoImage;
lv_obj_t *ui_TagCountLabel;
lv_obj_t *ui_TagSpinner;


// SCREEN: ui_OptionScreen
void ui_OptionScreen_screen_init(void);
lv_obj_t *ui_OptionScreen;
lv_obj_t *ui_OptionPanelHolder;
lv_obj_t *ui_OptionListPanelHolderT;
lv_obj_t *ui_OptionListLabelT;
lv_obj_t *ui_OptionNextImageT;
lv_obj_t *ui_OptionEditMarkImageT;
void ui_event_OptionSaveButton( lv_event_t * e);
lv_obj_t *ui_OptionSaveButton;
lv_obj_t *ui_OptionSaveImage;
void ui_event_OptionBackButton( lv_event_t * e);
lv_obj_t *ui_OptionBackButton;
lv_obj_t *ui_OptionBackImage;
void ui_event_OptionResetButton( lv_event_t * e);
lv_obj_t *ui_OptionResetButton;
lv_obj_t *ui_OptionResetImage;


// SCREEN: ui_InputScreen
void ui_InputScreen_screen_init(void);
lv_obj_t *ui_InputScreen;
void ui_event_InputSaveButton( lv_event_t * e);
lv_obj_t *ui_InputSaveButton;
lv_obj_t *ui_InputSaveImage;
void ui_event_InputBackButton( lv_event_t * e);
lv_obj_t *ui_InputBackButton;
lv_obj_t *ui_InputBackImage;
lv_obj_t *ui_InputTextArea;
lv_obj_t *ui_InputKeyboard;
void ui_event_InputResetButton( lv_event_t * e);
lv_obj_t *ui_InputResetButton;
lv_obj_t *ui_InputResetImage;


// SCREEN: ui_AlertScreen
void ui_AlertScreen_screen_init(void);
lv_obj_t *ui_AlertScreen;
lv_obj_t *ui_AlertLabel;
lv_obj_t *ui_AlertSpinner;
void ui_event_ActionOkButton( lv_event_t * e);
lv_obj_t *ui_ActionOkButton;
lv_obj_t *ui_ActionOkImage;
void ui_event_ActionCancelButton( lv_event_t * e);
lv_obj_t *ui_ActionCancelButton;
lv_obj_t *ui_ActionCancelImage;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_388871461[1] = {&ui_img_142471982};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void SpinnerSpin_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);

}
void TagBlur_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 255, 128 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void TagUnblur_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 128, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_TagsHolderPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      suppressAlarm( e );
}
}
void ui_event_ToOptionButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_OptionScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_OptionScreen_screen_init);
      to_option_btn_action( e );
}
}
void ui_event_OptionSaveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      option_save_btn_action( e );
}
}
void ui_event_OptionBackButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      cancel_save_btn_action( e );
}
}
void ui_event_OptionResetButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      option_reset_btn_action( e );
}
}
void ui_event_InputSaveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      input_save_btn_action( e );
}
}
void ui_event_InputBackButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      input_cancel_btn_action( e );
}
}
void ui_event_InputResetButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      input_reset_btn_action( e );
}
}
void ui_event_ActionOkButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      action_ok_btn_action( e );
}
}
void ui_event_ActionCancelButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      action_cancel_btn_action( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_SplashScreen_screen_init();
ui_HomeScreen_screen_init();
ui_OptionScreen_screen_init();
ui_InputScreen_screen_init();
ui_AlertScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_SplashScreen);
}
