// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Vservesafe_gateway_screen

#ifndef _VSERVESAFE_GATEWAY_SCREEN_UI_H
#define _VSERVESAFE_GATEWAY_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void SpinnerSpin_Animation( lv_obj_t *TargetObject, int delay);
void TagBlur_Animation( lv_obj_t *TargetObject, int delay);
void TagUnblur_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
extern lv_obj_t *ui_SplashScreen;
extern lv_obj_t *ui_ColdsensesLogo;
extern lv_obj_t *ui_LoadingLabel;
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t *ui_HomeScreen;
void ui_event_TagsHolderPanel( lv_event_t * e);
extern lv_obj_t *ui_TagsHolderPanel;
extern lv_obj_t *ui_TagPanelT;
extern lv_obj_t *ui_TagInnerPanelT;
extern lv_obj_t *ui_TagCRHLabelT;
extern lv_obj_t *ui_TagTempLabelT;
extern lv_obj_t *ui_TagHumidLabelT;
extern lv_obj_t *ui_TagNameLabelT;
extern lv_obj_t *ui_TagMacLabelT;
extern lv_obj_t *ui_StatusPanel;
extern lv_obj_t *ui_WifiStatusImage;
extern lv_obj_t *ui_WifiOffStatusImage;
extern lv_obj_t *ui_BLEStatusImage;
extern lv_obj_t *ui_ServerStatusImage;
extern lv_obj_t *ui_ServerOffStatusImage;
extern lv_obj_t *ui_AlarmStatusImage;
extern lv_obj_t *ui_AlarmOffStatusImage;
extern lv_obj_t *ui_TitleLabel;
void ui_event_ToOptionButton( lv_event_t * e);
extern lv_obj_t *ui_ToOptionButton;
extern lv_obj_t *ui_ToOptionImage;
extern lv_obj_t *ui_HomeLogoImage;
extern lv_obj_t *ui_TagCountLabel;
extern lv_obj_t *ui_TagSpinner;
// SCREEN: ui_OptionScreen
void ui_OptionScreen_screen_init(void);
extern lv_obj_t *ui_OptionScreen;
extern lv_obj_t *ui_OptionPanelHolder;
extern lv_obj_t *ui_OptionListPanelHolderT;
extern lv_obj_t *ui_OptionListLabelT;
extern lv_obj_t *ui_OptionNextImageT;
extern lv_obj_t *ui_OptionEditMarkImageT;
void ui_event_OptionSaveButton( lv_event_t * e);
extern lv_obj_t *ui_OptionSaveButton;
extern lv_obj_t *ui_OptionSaveImage;
void ui_event_OptionBackButton( lv_event_t * e);
extern lv_obj_t *ui_OptionBackButton;
extern lv_obj_t *ui_OptionBackImage;
void ui_event_OptionResetButton( lv_event_t * e);
extern lv_obj_t *ui_OptionResetButton;
extern lv_obj_t *ui_OptionResetImage;
// SCREEN: ui_InputScreen
void ui_InputScreen_screen_init(void);
extern lv_obj_t *ui_InputScreen;
void ui_event_InputSaveButton( lv_event_t * e);
extern lv_obj_t *ui_InputSaveButton;
extern lv_obj_t *ui_InputSaveImage;
void ui_event_InputBackButton( lv_event_t * e);
extern lv_obj_t *ui_InputBackButton;
extern lv_obj_t *ui_InputBackImage;
extern lv_obj_t *ui_InputTextArea;
extern lv_obj_t *ui_InputKeyboard;
void ui_event_InputResetButton( lv_event_t * e);
extern lv_obj_t *ui_InputResetButton;
extern lv_obj_t *ui_InputResetImage;
// SCREEN: ui_AlertScreen
void ui_AlertScreen_screen_init(void);
extern lv_obj_t *ui_AlertScreen;
extern lv_obj_t *ui_AlertLabel;
extern lv_obj_t *ui_AlertSpinner;
void ui_event_ActionOkButton( lv_event_t * e);
extern lv_obj_t *ui_ActionOkButton;
extern lv_obj_t *ui_ActionOkImage;
void ui_event_ActionCancelButton( lv_event_t * e);
extern lv_obj_t *ui_ActionCancelButton;
extern lv_obj_t *ui_ActionCancelImage;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_142471982);   // assets\logo-full1.png
LV_IMG_DECLARE( ui_img_wifi_png);   // assets\wifi.png
LV_IMG_DECLARE( ui_img_wifi_off_png);   // assets\wifi_off.png
LV_IMG_DECLARE( ui_img_bluetooth_png);   // assets\bluetooth.png
LV_IMG_DECLARE( ui_img_clouds_png);   // assets\clouds.png
LV_IMG_DECLARE( ui_img_cloud_slash_png);   // assets\cloud_slash.png
LV_IMG_DECLARE( ui_img_bell_png);   // assets\bell.png
LV_IMG_DECLARE( ui_img_bell_slash_png);   // assets\bell_slash.png
LV_IMG_DECLARE( ui_img_gear_png);   // assets\gear.png
LV_IMG_DECLARE( ui_img_chevron_right_png);   // assets\chevron_right.png
LV_IMG_DECLARE( ui_img_asterisk_png);   // assets\asterisk.png
LV_IMG_DECLARE( ui_img_check_png);   // assets\check.png
LV_IMG_DECLARE( ui_img_arrow_left_png);   // assets\arrow_left.png
LV_IMG_DECLARE( ui_img_arrow_cc_png);   // assets\arrow_cc.png
LV_IMG_DECLARE( ui_img_x_png);   // assets\x.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
