// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Vservesafe_gateway_screen

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void suppressAlarm(lv_event_t * e);
void to_option_btn_action(lv_event_t * e);
void option_save_btn_action(lv_event_t * e);
void cancel_save_btn_action(lv_event_t * e);
void option_reset_btn_action(lv_event_t * e);
void input_save_btn_action(lv_event_t * e);
void input_cancel_btn_action(lv_event_t * e);
void input_reset_btn_action(lv_event_t * e);
void action_ok_btn_action(lv_event_t * e);
void action_cancel_btn_action(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
