// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Coldsenses_gateway_screen

#include <Arduino.h>
#include "ui.h"
#include "VservesafeEnums.h"

extern void lv_obj_toggle_display(lv_obj_t *obj, bool isShow);
extern void lv_obj_toggle_clickable(lv_obj_t *obj, bool clickable);

extern bool isOptionsDirty();
extern void restoreSaveToOptions();
extern void applySaveOptions();
extern void restoreOptionToTemp(coldsenses_input_target target);
extern void applyValueToOption(String value, coldsenses_input_target target);

extern void transitionToHomeScreen();
extern void transitionToOptionScreen();
extern void transitionToAlertScreen();
extern void transitionToInputScreen();
extern void changeAlarmScreen(String message, bool showOK, bool showCancel, bool showSpinner);

extern String inputTemp;
extern bool stopAlarmFlag;

extern coldsenses_after_alarm_action afterAlarmAction;
extern coldsenses_input_target inputTarget;

void option_save_btn_action(lv_event_t *e)
{
  if (isOptionsDirty())
  {
    afterAlarmAction = VSERVESAFE_ACTION_SAVE_CONFIRM;

    changeAlarmScreen("Do you want to save options?", true, true, false);
    transitionToAlertScreen();
  }
}

void cancel_save_btn_action(lv_event_t *e)
{
  if (isOptionsDirty())
  {
    afterAlarmAction = VSERVESAFE_ACTION_SAVE_CANCEL;

    changeAlarmScreen("Confirm back to Home Screen?\nUnsaved changes will be lost", true, true, false);
    transitionToAlertScreen();
  }
  else
  {
    transitionToHomeScreen();
  }
}

void option_reset_btn_action(lv_event_t *e)
{
  if (isOptionsDirty())
  {
    afterAlarmAction = VSERVESAFE_ACTION_SAVE_CONFIRM;

    changeAlarmScreen("Reset options to previous value?", true, true, false);
    transitionToAlertScreen();
  }
}

void input_save_btn_action(lv_event_t *e)
{
  afterAlarmAction = VSERVESAFE_ACTION_INPUT_CONFIRM;

  changeAlarmScreen("Confirm edit?", true, true, false);
  transitionToAlertScreen();
}

void input_cancel_btn_action(lv_event_t *e)
{
  afterAlarmAction = VSERVESAFE_ACTION_INPUT_CANCEL;

  changeAlarmScreen("Cancel edit?\nUnsaved changes will be lost", true, true, false);
  transitionToAlertScreen();
}

void input_reset_btn_action(lv_event_t *e)
{
  afterAlarmAction = VSERVESAFE_ACTION_INPUT_RESET;

  changeAlarmScreen("Reset value to previous value?", true, true, false);
  transitionToAlertScreen();
}

void action_ok_btn_action(lv_event_t *e)
{
  switch (afterAlarmAction)
  {
  case VSERVESAFE_ACTION_SAVE_CONFIRM:
    changeAlarmScreen("Saving...", false, false, true);
    applySaveOptions();
    transitionToHomeScreen();
    break;
  case VSERVESAFE_ACTION_SAVE_RESET:
    changeAlarmScreen("Reseting...", false, false, true);
    restoreSaveToOptions();
    transitionToOptionScreen();
    break;
  case VSERVESAFE_ACTION_SAVE_CANCEL:
    transitionToHomeScreen();
    break;
  case VSERVESAFE_ACTION_INPUT_CONFIRM:
    applyValueToOption(lv_textarea_get_text(ui_InputTextArea), inputTarget);
    transitionToOptionScreen();
    break;
  case VSERVESAFE_ACTION_INPUT_CANCEL:
    transitionToOptionScreen();
    break;
  case VSERVESAFE_ACTION_INPUT_RESET:
    restoreOptionToTemp(inputTarget);
    transitionToInputScreen();
    break;
  case VSERVESAFE_ACTION_AFTER_CHECK_VERSION:
    transitionToOptionScreen();
    break;
  default:
    break;
  }
}

void action_cancel_btn_action(lv_event_t *e)
{
  switch (afterAlarmAction)
  {
  case VSERVESAFE_ACTION_SAVE_CONFIRM:
  case VSERVESAFE_ACTION_SAVE_CANCEL:
  case VSERVESAFE_ACTION_SAVE_RESET:
    transitionToOptionScreen();
    break;
  case VSERVESAFE_ACTION_INPUT_CONFIRM:
  case VSERVESAFE_ACTION_INPUT_CANCEL:
  case VSERVESAFE_ACTION_INPUT_RESET:
    transitionToInputScreen();
    break;
  default:
    break;
  }
}

void to_option_btn_action(lv_event_t *e)
{
  restoreSaveToOptions();

  transitionToOptionScreen();
}

void suppressAlarm(lv_event_t *e)
{
  stopAlarmFlag = true;
}
