name: vservesafe
description: VServeSafe Clone

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.17.1
  cookie_jar: ^4.0.8
  country_flags: ^2.1.1
  cross_file_image: ^1.0.0
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  intl: ^0.18.0
  multi_select_flutter: ^4.1.3
  password_generator: ^1.0.0
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
