name: vservesafe
description: VServeSafe Clone

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  calendar_date_picker2: ^0.5.3
  collection: ^1.17.1
  cookie_jar: ^4.0.8
  country_flags: ^2.1.1
  cross_file_image: ^1.0.0
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  duration: ^3.0.13
  email_validator: ^2.1.17
  file_picker: ^6.1.1
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_quill: ^8.6.3
  flutter_quill_extensions: ^0.7.2
  flutter_spinbox: ^0.13.1
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  intl: ^0.18.0
  multi_select_flutter: ^4.1.3
  password_generator: ^1.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo-web.png"
    background_color: "#ffffff"
    theme_color: "#975aff"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
